[build]
  command = "CI= npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "16.9.0"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"